version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 2
  labels:
  - dependencies
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 2
  labels:
  - dependencies
