apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: gitaction
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: LATEST_IMAGE_REF
          imagePullPolicy: Always
          env:
          - name: REPO_OWNER
            value: CMSgov
          - name: REPO_NAME
            value: github-actions-runner-aws
          - name: PERSONAL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: PERSONAL_ACCESS_TOKEN
      imagePullSecrets:
        - name: ecrcred
