name: Get latest GitHub Actions Runner

on:
  # schedule:
  #   - cron: '30 9 * * *'
  push:
    branches: [workflow-runner-update]
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/actions/runner/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(<actions-runner.version)