name: Get latest GitHub Actions Runner

on:
  # schedule:
  #   - cron: '30 9 * * *'
  push:
    branches: [workflow-runner-update]
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set release version and current version variables
        id: get-current-version
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/actions/runner/releases/latest | jq '.[1:]' -r ".tag_name")
      # - name: Change release version in Dockerfile
      #   id: update-version
      #   env:
      #     NEW_VERSION: ${{ steps.get-current-version.outputs.release_tag }}
      #   run: |
      #     sed -ie 's,ACTIONS_VERSION='".*"',ACTIONS_VERSION="'"$NEW_VERSION"'",g' Dockerfile